### ISSUE TITLE
python manage.py migrate でエラーが発生してしまいます

### ISSUE THREAD

**Issue by sohta3** [sijysn/Tinder_clone#1]
お世話になります。
READMEのsetup過程でエラーが発生してしまいます。
ご確認お願いします。

![image](https://user-images.githubusercontent.com/11865933/115325165-17cf7300-a1c6-11eb-877f-0f0b00409401.png)

**Comment by sijysn** [comment]
お世話になっております。

そちらpythonのバージョンはいくつでしょうか？
python2ですと、同様のエラーが出てしまうようです。

（私が使用しているバージョンは、pythonが3.6.5、pipが21.0.1　です）

もしpythonのバージョンが3以上でしたら、
python　→　python3
としてコマンド入力していただきたいです。

お忙しい中お手数ですが、ご確認のほどよろしくお願いいたします。

**Comment by sijysn** [comment]
お世話になっております。

先程の方法がうまくいきませんでしたら、
ただいまREADMEに追記いたしましたので、そちらをご確認ください。
（仮想環境の構築について追記いたしました。）

お忙しい中お手数ですが、ご確認のほどよろしくお願いいたします。

**Comment by sohta3** [comment]
ありがとうございます
python3環境でセットアップ完了できました
